ChatApplication/Controllers/FriendController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ChatApplication.Models;
using ChatApplication.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace ChatApplication.Controllers
{ 
    [Authorize]
    public class FriendController : Controller
    {
        //UserManager<ApplicationUser> userManager;
        //private readonly SignInManager<ApplicationUser> signInManager
        private readonly IFriendRepository friendRepository;
        private readonly AppDbContext context;
        //private readonly List<ApplicationUser> user = new List<ApplicationUser>();
        //public IReadOnlyCollection<ApplicationUser> Users = user;

        public FriendController(UserManager<ApplicationUser> userManager, SignInManager<ApplicationUser> signInManager,
            IFriendRepository friendRepository,AppDbContext context)
        {
            //this.userManager = userManager;
            //this.signInManager = signInManager;
            this.friendRepository = friendRepository;
            this.context = context;
        }
        [HttpGet]
        public ViewResult AddFriend(string id)
        {
            ApplicationUser loggedinuser = context.AspNetUsers.SingleOrDefault<ApplicationUser>(u => u.Id == id);
            AddFriendViewodel friendmodel = new AddFriendViewodel
            {
                user = loggedinuser,
                UserId=id
            };
            return View(friendmodel);
        }
        [HttpPost]
        public IActionResult AddFriend(AddFriendViewodel friendmodel)
        {

            if (ModelState.IsValid)
            {
                ApplicationUser existfriend = context.AspNetUsers.SingleOrDefault<ApplicationUser>(u => u.PhoneNumber == friendmodel.mobileno);
                //Console.WriteLine(existfriend);
                string msg = "";
                if (existfriend == null)
                {
                    ApplicationUser appuser = context.AspNetUsers.SingleOrDefault<ApplicationUser>(u => u.Id == friendmodel.UserId);
                    friendmodel.user = appuser;
                    msg = "Friend does not register on this website, so invite him using";
                    ViewData["err"] = msg;
                    return View(friendmodel);
                }
                else
                {
                    friend f = new friend
                    {
                        fname = friendmodel.fname,
                        mobileno = friendmodel.mobileno,
                        userID = friendmodel.UserId
                    };
                    friendRepository.Add(f);
                    return Redirect("/home/home/"+friendmodel.UserId);
                }
            }
            return View();
        }
        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public IActionResult Delete(int id)
        {
           friend f = friendRepository.GetFriend(id);
            if (f == null)
            {
                return NotFound();
            }
            return View(f);
        }
        //[Route("[action]")]
        [HttpPost, ActionName("Delete")]
        public IActionResult DeleteConfirmed(int id)
        {
            friend f = friendRepository.GetFriend(id);
            friendRepository.Delete(f.friendID);
            return RedirectToAction("index","account");
        }
    }
}

ChatApplication/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using ChatApplication.Models;
using ChatApplication.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;

namespace ChatApplication.Controllers
{
    [Authorize]
    public class HomeController : Controller
    {
        public readonly AppDbContext context;
        private readonly UserManager<ApplicationUser> userManager;
        private readonly SignInManager<ApplicationUser> signInManager;
        private readonly ILogger<HomeController> _logger;
        private readonly IFriendRepository friendRepository;
        public HomeController(ILogger<HomeController> logger, UserManager<ApplicationUser> userManager,
            SignInManager<ApplicationUser> signInManager,IFriendRepository friendRepository,
            AppDbContext context)
        {
            _logger = logger;
            this.signInManager = signInManager;
            this.userManager = userManager;
            this.friendRepository = friendRepository;
            this.context = context;
        }
        [AllowAnonymous]
        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public async Task<IActionResult> Home(string id)
        {
            ApplicationUser user = await userManager.FindByIdAsync(id);
            IEnumerable<friend> Friends = (IEnumerable<friend>)context.friends.Where<friend>(f => f.userID == id);
            IEnumerable<messege> messages = Enumerable.Empty<messege>();
            FriendListMessageList viewmodel = new FriendListMessageList();
            viewmodel.Fname = "";
            viewmodel.FId = -1;
            viewmodel.friends = Friends;
            viewmodel.messeges = messages;
            viewmodel.user = user;
            viewmodel.userID = user.Id;
            return View(viewmodel);
        }
        public IActionResult showMessages(string fid,string appuserid)
        {
            //var userid = userManager.GetUserId(this.User);
            int friendid = Int32.Parse(fid);
            var friend = context.friends.SingleOrDefault(f => f.friendID == friendid);
            var friendappuser = context.AspNetUsers.SingleOrDefault(u => u.PhoneNumber == friend.mobileno);
            var appuser = context.AspNetUsers.SingleOrDefault(u => u.Id == appuserid);
            IEnumerable<messege> messages = from m in context.messeges
                                            where (m.receiverId == friendappuser.Id && m.senderID == appuserid) ||
                 (m.senderID == friendappuser.Id && m.receiverId == appuserid)
                                            select m;
            IEnumerable<friend> Friends = from f in context.friends where f.userID == appuserid select f;

            FriendListMessageList viewmodel = new FriendListMessageList();
            viewmodel.Fname = friend.fname;
            viewmodel.FId = friend.friendID;
            viewmodel.friends = Friends;
            viewmodel.messeges = messages;
            viewmodel.userID = appuserid;
            viewmodel.user = appuser;
            return View("home", viewmodel);
        }
        [HttpPost]
        public async Task<ActionResult> createMessage(int friendid,string userid, string text)
        {
            //var userid = userManager.GetUserId(this.User);
            var friend = context.friends.SingleOrDefault(f => f.friendID == friendid);
            var friendappuser = context.AspNetUsers.SingleOrDefault(u => u.PhoneNumber == friend.mobileno);

            messege new_message = new messege
            {
                receiverId = friendappuser.Id,
                senderID = userid,
                text = text,
                datetime = DateTime.Now.ToString("M/dd/yyyy hh:MM tt"),
                filePath = null
            };
            await context.messeges.AddAsync(new_message);
            await context.SaveChangesAsync();
            return Redirect("/home/showMessages?fid=" + friendid + "&appuserid=" + userid);
            //return RedirectToAction("showMessages", "home", friend.friendID);
        }
        public IActionResult onlineFriends(string id)
        {
            IEnumerable<friend> Friends = from f in context.friends where f.userID == id select f;
            List<friend> onlinefriends = new List<friend>();
            foreach (var friend in Friends)
            {
                var friendappuser = context.AspNetUsers.SingleOrDefault(u => u.PhoneNumber == friend.mobileno);
                if (friendappuser.LoggedIn == true)
                {
                    onlinefriends.Add(friend);
                }
            }
            IEnumerable<messege> messages = Enumerable.Empty<messege>();
            var appuser = context.AspNetUsers.SingleOrDefault(u => u.Id == id);
            FriendListMessageList viewmodel = new FriendListMessageList();
            viewmodel.Fname = "";
            viewmodel.FId = -1;
            viewmodel.friends = onlinefriends;
            viewmodel.messeges = messages;
            viewmodel.userID = id;
            viewmodel.user = appuser;
            return View("home", viewmodel);
        }
        public IActionResult Privacy()
        {
            return View();
        }
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ChatApplication/Views/Home/Home.cshtml
@model ChatApplication.ViewModels.FriendListMessageList
@inject SignInManager<ApplicationUser> signInManager
@{
    ViewData["Title"] = "Home";
}
<head>
    <style>
        .img-position {
            position: absolute;
            top: 8%;
        }

        .main-container {
            position: absolute;
            top: 12%;
            left: 1.6%;
            height: 610px;
            width: 1200px;
        }
        .friends {
            text-decoration: none;
        }

        .friends:hover {
            background-color: grey;
            text-decoration: none;
        }
        #chatWindow .container {
            border: 2px solid #dedede;
            background-color: #f1f1f1;
            border-radius: 30px;
            padding: 10px;
            margin: 10px 0;
            width: 100%;
            font-family: "Open Sans", serif;
        }

        #chatWindow .sender {
            font-size: 0.8em;
            font-weight: bold;
            font-family: 'Shadows Into Light', cursive;
        }

        /* Darker chat container */
        #chatWindow .darker {
            border-color: #fff;
            background-color: #007bff;
        }

        /* Clear floats */
        #chatWindow .container::after {
            content: "";
            clear: both;
            display: table;
        }

        /* Style images */
        #chatWindow .container img {
            float: left;
            max-width: 60px;
            width: 100%;
            margin-right: 20px;
            border-radius: 50%;
        }

            /* Style the right image */
            #chatWindow .container img.right {
                float: right;
                margin-left: 20px;
                margin-right: 0;
            }

        /* Style time text */
        #chatWindow .time-right {
            float: right;
            color: #aaa;
        }

        /* Style time text */
        #chatWindow .time-left {
            float: left;
            color: #999;
        }
    </style>
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-md navbar-dark bg-dark fixed-top justify-content-start mb-3">
        <a class="navbar-brand text-light" style="font-size: 1.7vw;" asp-area="" asp-controller="Home" asp-action="Home">
            <i class="fas fa-comment" style="color: #00BFFF"></i>
            &nbsp; Let's Chat
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".mainnav" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse mainnav">
            <ul class="navbar-nav flex-grow-2">
                <li class="nav-item text-white">
                    <label style="font-size:1.3vw">@Model.user.UserName</label>
                </li>
                <li class="nav-item">
                    <!--<a class="nav-link text-light" style="font-size:1.3vw" asp-area="" asp-controller="Account" asp-action="logout">
                        <i class="fas fa-power-off" data-toggle="tooltip" data-placement="bottom" title="Logout"></i>
                    </a>-->
                    <form method="post" asp-controller="account" asp-action="logout" asp-route-id="@Model.userID">
                        <button type="submit" style="width:auto;font-size:1.3vw" class="nav-link btn btn-link py-0">
                            <i class="fas fa-power-off" data-toggle="tooltip" data-placement="bottom" title="Logout"></i>
                        </button>
                    </form>
                </li>
            </ul>
        </div>
    </nav>
    <img src="~/images/background_chat1.jpg" class="img-responsive img-position" style="width: 100%;
            background-position: center;
            background-repeat:no-repeat;
            background-attachment:fixed;
            background-size:cover;
            background-color:aquamarine;
            max-height:665px;
            " />
    <div class="main-container">
        <div class="row h-100">

            <div class="col col-lg-8 h-100">

                <div class="container h-100" style="border:1px solid black;background-color:rgb(173,230,230);">

                    <div class="d-flex bg-dark align-content-lg-start">
                        <a class="p-2 border rounded text-white font-weight-bold"
                           style="font-size: 1vw;" data-toggle="tooltip" data-placement="top" title="@Model.Fname">
                            @Model.Fname
                        </a>
                        <a class="p-2 border rounded text-white"
                           style="font-size: 1vw;" asp-area="" asp-controller="Home" asp-action="Home" asp-route-id="@Model.userID"
                           data-toggle="tooltip" data-placement="top" title="All Friends">
                            All Friends
                        </a>
                        <a class="p-2 border rounded text-white"
                           style="font-size: 1vw;" asp-area="" asp-controller="Home" asp-action="onlineFriends"
                           data-toggle="tooltip" data-placement="top" title="Online friends" asp-route-id="@Model.userID">
                            Online friends
                        </a>
                    </div>
                    <div class="container overflow-auto h-75 bg-light" id="chatWindow">
                        @if (Model.messeges == null)
                        {
                            <h3>You haven't started chatting with @Model.Fname.</h3>
                        }
                        @if (Model.messeges != null)
                        {
                            @foreach (var m in Model.messeges.OrderBy(m => m.datetime))
                            {
                                string containerClass, timePosition, textAlign, contcolor, offset;
                                if (Model.userID == m.senderID)
                                {
                                    containerClass = "container darker";
                                    timePosition = "time-right text-light";
                                    textAlign = "text-right text-white";
                                    contcolor = "bg-primary";
                                    offset = "col-md-6 offset-md-6";
                                }
                                else
                                {
                                    containerClass = "container";
                                    timePosition = "time-left";
                                    textAlign = "text-left";
                                    contcolor = "bg-light";
                                    offset = "";
                                }
                                <div class="row">
                                    <div class="@offset">
                                        <div class="@containerClass @contcolor">

                                            <!--<p class="sender @textAlign"></p>-->
                                            <p class="@textAlign">@m.text</p>
                                            <span class="@timePosition">@m.datetime</span>
                                        </div>
                                    </div>
                                </div>
                            }
                        }
                    </div>
                    <form method="post" asp-controller="home" asp-action="createMessage">
                        <input type="hidden" name="friendid" value="@Model.FId" id="receiverid" />
                        <input type="hidden" name="userid" value="@Model.userID" id="userid" />
                        <input type="hidden" name="messageid" value="@Model.messeges.Count()" id="messageid" />
                        <div class="container bg-light">
                            <br />
                            <div class="row w-100">
                                <div class="col-lg-10">
                                    <input type="text" class="form-control" style="font-size: 1vw;"
                                           name="text" placeholder="Enter your message" id="text" />
                                </div>
                                <div class="col-lg-2">
                                    <button type="submit" style="font-size: 1vw; border:none"
                                            class="form-control rounded-pill bg-success text-white" data-toggle="tooltip" data-placement="top" title="Send">
                                        <i class="fas fa-paper-plane fa-1x"></i>
                                    </button>
                                </div>
                            </div>
                            <br />
                        </div>
                    </form>
                </div>
            </div>

            <div class="col col-lg-4 h-100">

                <div class="container h-100 p-1 bg-warning rounded" style="border:1px solid black">

                    <div class="d-flex bg-dark flex-row-reverse">
                        <a class="text-dark p-2 bg-white rounded-circle m-2" style="font-size: 2vw;" asp-area="" asp-controller="Friend" asp-action="AddFriend" asp-route-id="@Model.userID">

                            <i class="fas fa-user-plus" style="color: darkslategray" data-toggle="tooltip" data-placement="top" title="Add Friend"></i>
                        </a>
                        <a class="text-dark p-2 bg-white rounded-circle m-2" style="font-size: 2vw;" asp-area="" asp-controller="Home" asp-action="AddGroup">
                            <i class="fas fa-users" style="color: darkslategray" data-toggle="tooltip" data-placement="top" title="Add Group"></i>
                        </a>
                        <a class="text-dark p-2 bg-white rounded-circle m-2" style="font-size: 2vw;" asp-area="" asp-controller="Account" asp-action="UpdateProfile" asp-route-id="@Model.userID">
                            <i class="fas fa-user-edit" style="color: darkslategray" data-toggle="tooltip" data-placement="top" title="Edit your profile"></i>
                        </a>
                    </div>
                    <div class="container bg-light">
                        @foreach (var friend in Model.friends)
                        {
                            <div class="row w-100 bg-light text-dark">
                                <div class="col col-lg-2">
                                    <a asp-action="friendProfile" asp-controller="home">
                                        <img src="~/images/User.png" width="50" height="50" />
                                    </a>
                                </div>
                                <div class="col col-lg-10 friends">

                                    @{ var parms = new Dictionary<string, string>
                                                                                                                                    {
                                                { "fid", (friend.friendID).ToString() },
                                                { "appuserid", Model.user.Id }
                                            }; }
                                    <a asp-controller="home" asp-action="showMessages" asp-all-route-data="parms">
                                        <h5>@friend.fname</h5>
                                        @friend.mobileno
                                    </a>
                                </div>
                            </div>
                        }
                    </div>
                </div>
            </div>

        </div>
    </div>

    <!--<script src="~/js/signalr/dist/browser/signalr.js"></script>
    <script src="~/js/signalr/dist/browser/signalr.min.js"></script>
    <script src="~/js/chat.js"></script>
    <script src="~/js/SignalRHandler.js"></script>-->
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>




</body>

ChatApplication/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
    Layout = "/Views/Shared/_Layout.cshtml";
}
<head>
    <style>
        .centered {
            position: absolute;
            top: 12%;
            left: 21%;
        }

        .centered-next-1 {
            position: absolute;
            top: 23%;
            left: 25%;
        }

        .centered-next-2 {
            position: absolute;
            top: 60%;
            left: 26%;
        }

        .centered-next-3 {
            position: absolute;
            top: 95%;
            left: 13%;
        }
    </style>
    <!-- For ICONS -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
</head>

<nav class="navbar navbar-expand-sm navbar-toggleable-md navbar-dark bg-dark fixed-top justify-content-start mb-3">
    <a class="navbar-brand text-light" style="font-size: 1.7vw;" asp-area="" asp-controller="Home" asp-action="Index">
        <i class="fas fa-comment" style="color: #00BFFF"></i>
        &nbsp; Let's Chat
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
            aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
        <ul class="navbar-nav flex-grow-2">
            <li class="nav-item">
                <a class="nav-link text-light" style="font-size:1.3vw" asp-area="" asp-controller="Home" asp-action="Index">
                    Home
                    <i class="fas fa-home" data-toggle="tooltip" data-placement="bottom" title="Home"></i>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-light" style="font-size:1.3vw" href="#FAQ">
                    FAQ
                    <i class="fas fa-question-circle" data-toggle="tooltip" data-placement="bottom" title="Ask Question"></i>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-light" style="font-size:1.3vw" href="#contact">
                    Contact
                    <i class="fas fa-phone-square" data-toggle="tooltip" data-placement="bottom" title="Contact us"></i>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-light" style="font-size:1.3vw" asp-area="" asp-controller="Account" asp-action="register">
                    Register
                    <i class="fas fa-address-book" data-toggle="tooltip" data-placement="bottom" title="Register"></i>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-light" style="font-size:1.3vw" asp-area="" asp-controller="Account" asp-action="login">
                    Login
                    <i class="fas fa-sign-in-alt" data-toggle="tooltip" data-placement="bottom" title="Login"></i>
                </a>
            </li>
        </ul>
    </div>
</nav>
<!-- <i class="fas fa-sign-out-alt"></i> Sign out/ logout-->
<img src="~/images/background_chat1.jpg" class="img-responsive" style="width: 100%;
    background-position: center;
    background-repeat:repeat;
    background-attachment:scroll;
    background-size:100%;
    background-color:aquamarine;
" />
<div class="container" style="overflow-y: auto;">
    <!--<img src="~/images/background_chat.jpg" class="img-responsive" style="width:100%; height:auto;background-position: center; background-repeat: no-repeat; background-size: cover;" />-->
    <!-- Heading  -->
    <h1 class="centered" style="font-size:3vw;">Welcome to the amazing Chat-Application</h1>

    <!-- Carousel for displaying functionality -->
    <div id="functionality" class="carousel slide w-50 mx-auto centered-next-1" data-ride="carousel">

        <ul class="carousel-indicators">
            <li data-target="#functionality" data-slide-to="0" class="active"></li>
            <li data-target="#functionality" data-slide-to="1"></li>
            <li data-target="#functionality" data-slide-to="2"></li>
            <li data-target="#functionality" data-slide-to="3"></li>
        </ul>

        <div class="carousel-inner">
            <div class="carousel-item active" data-interval="2000">
                <center>
                    <h1 style="font-size:3.2vw;">
                        <i class="fas fa-comment-dots fa-5x"></i>
                    </h1>
                </center>
                <br /><br /><br /><br />
                <div class="carousel-caption text-dark">
                    <h2 style="font-size:2.5vw;">Chat with friends</h2>
                </div>
            </div>
            <div class="carousel-item" data-interval="2000">
                <center>
                    <h1 style="font-size:3.2vw;">
                        <i class="fas fa-comments fa-5x"></i>
                    </h1>
                </center>
                <br /><br /><br /><br />
                <div class="carousel-caption text-dark">
                    <h2 style="font-size:2.5vw;">Chat with groups</h2>
                </div>
            </div>
            <div class="carousel-item" data-interval="2000">
                <center>
                    <h1 style="font-size:3.2vw;">
                        <i class="fas fa-file-upload fa-5x"></i>
                    </h1>
                </center>
                <br /><br /><br /><br />
                <div class="carousel-caption text-dark">
                    <h2 style="font-size:2.5vw;">Send files or other documents</h2>
                </div>
            </div>
            <div class="carousel-item" data-interval="2000">
                <center>
                    <h1 style="font-size:3.2vw;">
                        <i class="fas fa-user-clock fa-5x"></i>
                    </h1>
                </center>
                <br /><br /><br /><br />
                <div class="carousel-caption text-dark">
                    <h2 style="font-size:2.5vw;">View Online Friends</h2>
                </div>
            </div>
        </div>
    </div>

    <!-- FAQ -->
    <div class="container" style="font-size:1.3vw;" id="FAQ">
        <div class="bg-white centered-next-2 w-50 rounded ">
            <form action="">
                <div class="row p-2">
                    <div class="col col-lg-12">
                        <center><b style="font-size:2vw;">Ask any question</b></center>
                    </div>
                </div>
                <div class="row p-2">
                    <div class="col col-lg-12">
                        <input type="text" style="font-size:1.2vw;" class="form-control" id="email_id" placeholder="Enter your email-id" />
                    </div>
                </div>
                <div class="row p-2">
                    <div class="col col-lg-12">
                        <textarea class="form-control" style="font-size:1.2vw;" id="message" rows="3" placeholder="Enter your question here.."></textarea>
                    </div>
                </div>
                <div class="row p-2">
                    <div class="col col-lg-12">
                        <input type="submit" style="font-size:1.2vw;" class="btn btn-success" />
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

<!-- Contact -->
<!--<div class="container centered-next-3 w-75 mx-auto" style="font-size:1.3vw;border:1px solid black;" id="contact">
    <div class="row justify-content-center">
        <div class="col-lg-7 col-md-6 col-sm-5 col-xs-4 rounded bg-white">
            <form action="">
                <div class="form-group row p-2">
                    <label class="col-lg-12"><center><b style="font-size:2vw;">Contact information</b></center></label>
                </div>
                <div class="form-group row p-2">
                    <label for="email_id" class="col-sm-6 col-md-5 col-lg-4">Contact no.</label>
                    <label for="email_id"  class="form-control col-sm-6 col-md-7 col-lg-8">
                        xjndjsjnsjd
                        djdnsndsds
                        dnsjdnsjndjsnjj
                    </label>
                </div>
            </form>
        </div>
    </div>
</div>-->